joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

force_panda1:
    type: panda_controllers/CartesianImpedanceControllerSoftbots
    arm_id: panda_1
    joint_names:
        - panda_1_joint1
        - panda_1_joint2
        - panda_1_joint3
        - panda_1_joint4
        - panda_1_joint5
        - panda_1_joint6
        - panda_1_joint7
publish_rate: 30  # [Hz]

force_panda2:
    type: panda_controllers/CartesianImpedanceControllerSoftbots2
    arm_id: panda_2
    joint_names:
        - panda_2_joint1
        - panda_2_joint2
        - panda_2_joint3
        - panda_2_joint4
        - panda_2_joint5
        - panda_2_joint6
        - panda_2_joint7
publish_rate: 30  # [Hz]


   