$(arg arm_id_1)_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - $(arg arm_id_1)_joint1
        - $(arg arm_id_1)_joint2
        - $(arg arm_id_1)_joint3
        - $(arg arm_id_1)_joint4
        - $(arg arm_id_1)_joint5
        - $(arg arm_id_1)_joint6
        - $(arg arm_id_1)_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        $(arg arm_id_1)_joint1: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint2: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint3: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint4: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint5: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint6: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_1)_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

$(arg arm_id_2)_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - $(arg arm_id_2)_joint1
        - $(arg arm_id_2)_joint2
        - $(arg arm_id_2)_joint3
        - $(arg arm_id_2)_joint4
        - $(arg arm_id_2)_joint5
        - $(arg arm_id_2)_joint6
        - $(arg arm_id_2)_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        $(arg arm_id_2)_joint1: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint2: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint3: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint4: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint5: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint6: {trajectory: 0.1, goal: 0.1}
        $(arg arm_id_2)_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

#notice that the grippers joint2 mimics joint1
#this is why it is not listed under the hand controllers
$(arg arm_id_1)_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - $(arg arm_id_1)_finger_joint1
    gains:
        $(arg arm_id_1)_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

$(arg arm_id_2)_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - $(arg arm_id_2)_finger_joint1
    gains:
        $(arg arm_id_2)_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

